# Site settings
title: Jack Q
email: qiaobo@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Jack Q.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "//Jack-Q.github.io" # the base hostname & protocol for your site
github_username:  Jack-Q
disqus_shortname: jackq

# Build settings
markdown: redcarpet
extensions: [fenced_code_blocks]
highlighter: pygments