# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jack Q Blog
subtitle:
description:
author: Jack Q
language: en
timezone:
author_profile:
  github: Jack-Q
  facebook: JackQ2010
  twitter: Jack_Q_2010
  email: qiaobo@outlook.com
  # Stackoverflow Account ID, something like '6589119'
  stackoverflow: false

# URL
url: https://jack-q.github.io/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1 # 1 - to lower case, 2 - to upper case, 0 - do nothing
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
default_cc_by_sa: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  # tab_replace: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 9
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jack-q-blog

# Google Analytics 
googleAnalytics: true
googleAnalyticsId: UA-63336636-1
math_inline: false

# Feed generator
feed:
  type: atom # atom / rss2
  path: atom.xml
  limit: 20
  hub:
  content:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Jack-Q/blog.git
  branch: gh-pages
  message: update blog at {{ now('YYYY-MM-DD HH:mm:ss') }}

## Markdown Conversion Configuration
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true

## JavaScript uglify
uglify:
  mangle: true
  exclude: 
    - "*.min.js"
