# Hexo Development Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Google Analytics 
googleAnalytics: false
googleAnalyticsId: ""

# Comment
no_comments: Comment is disabled in development mode.